Offchain Attestations
BreadchainCoop/BuildersDollar pull request #1
Opened 2024-11-26 23:00 UTC by daopunk

- changed logic of validateProject function to use with off-chain verification

2024-11-27 07:35 UTC, RonTuretzky requested changes

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
> +contract BuildersManager is EIP712Upgradeable, Ownable2StepUpgradeable, IBuildersManager {
Why not inherit the contract [here](https://github.com/ethereum-attestation-service/eas-contracts-example/blob/master/contracts/OffchainAttestationVerifier.sol)  ? adding the eas repo as a submodule would also allow us to get the interface and the attestations structs

seems like it would cut down a lot on code as well.

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
> +    string memory _version,
why not bundle these with the params struct, if we're going with that approach?

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
> +    voterToProjectVouch[msg.sender][_projectAttestation] = true;
These functions should be coupled , this is designed on purpose so the voucher does not have to submit two transactions

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
>  import {Ownable2StepUpgradeable} from '@oz-upgradeable/access/Ownable2StepUpgradeable.sol';
what's the difference between ownableupgradeble and this lib?

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
>      _l = _currentProjects.length;
the way the loop is set up on lines 123-124, eject the project changes the length of the array , which will lead to out of range index errors, which is why I had it set up the way it was earlier.

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
>      _l = _currentProjects.length;
Also line 126 should be removed, if the project is in currentProjects it must have reached `minVouches`

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
> +      (uint256 farcasterID,,,,) = abi.decode(_attestation.data, (uint256, string, string, string, string));
emit the attestationID , not the farcaster iD probably 🤔

2024-11-27 07:35 UTC, RonTuretzky commented on src/interfaces/IBuildersManager.sol
>    /// @notice Throws when the project is not in the current projects list
I believe that this is not the right description for the error on the next line right? 
Also, I would change that name to "CycleNotReady"

2024-11-27 07:35 UTC, RonTuretzky commented on src/contracts/BuildersManager.sol
> +contract BuildersManager is EIP712Upgradeable, Ownable2StepUpgradeable, IBuildersManager {
note if you decide to do this you need [this specific commit](https://github.com/ethereum-attestation-service/eas-contracts-example/blob/f657f5322ca808cb24939a33502d241e123eca09/contracts/OffchainAttestationVerifier.sol) and to change the constructor arg to 1

alternatively you can just use the deployment [here](https://optimistic.etherscan.io/address/0x86ef22318f2F7F621EA5cDD6c6B7947920bFD096) and offload all this code

2024-12-01 13:10 UTC, daopunk commented on src/contracts/BuildersManager.sol
> +    string memory _version,
will change "params" to "settings" to avoid confusion

2024-12-01 14:34 UTC, daopunk commented on src/contracts/BuildersManager.sol
>  import {Ownable2StepUpgradeable} from '@oz-upgradeable/access/Ownable2StepUpgradeable.sol';
Ownable allows transfer of ownership immediately. Ownable2Step, requires new owner to accept ownership, but remains with the previous owner until this happens, so it is more safe and should be used as default, unless there is a special case to use basic Ownable.

2024-12-07 15:05 UTC, merged